### ISSUE TITLE
Extraction of arrays

### ISSUE THREAD

**Issue by dwolters** [ind9/web-auto-extractor#6]
I'm using the web auto extractor to retrieve recipes embedded as microdata. Unfortunately, the extractor is not extracting the ingridient list as an array. Instead the ingridients replace each other in the object so that only the last ingridient remains.

Example:
```html
<ul class="ingredientList">`
  <li itemprop="ingredients">&frac12; cup butter</li>`
  <li itemprop="ingredients">&frac12; cup powdered sugar</li>`
  <li itemprop="ingredients">&frac12; cup chocolate chips</li>`
</ul>
```

The web auto extractor only extracts:
`{ ..., ingedients : "&frac12; cup chocolate chips", ...}`
Instead of: 
`{ ..., ingedients : ["&frac12; cup butter","&frac12; cup powdered sugar","&frac12; cup chocolate chips"], ...}`

An example page with recipe microdata can be found here: [getmecooking.com](https://www.getmecooking.com/recipe/peppermint-patties)

Is this behavior by design? 

The official [schema.org Recipe](http://schema.org/Recipe) example allows this kind of multi declaration of ingridients.

**Comment by addnab** [comment]
I assumed all lists would follow the [ItemList](http://schema.org/ItemList) schema. Looking at the case you've provided, I see it's not really the case. It must be fixed. I'll review your PR and get back to you. Thanks.

**Comment by addnab** [comment]
Fixed https://github.com/ind9/web-auto-extractor/pull/7
